package com.falabellasellers.preaprobados;

import cl.datamart.pylon.mappings.cte.CTE;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CarpetaTributaria extends CTE implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CarpetaTributaria() {
        super();
    }




}