package com.falabellasellers.preaprobados;

import cl.datamart.pylon.mappings.sales.stretch.TramoVenta;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("Este objeto debe inicializarse desde el codigo con el objeto ClienteSII0")
public class ClienteSII extends TramoVenta implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public ClienteSII() {
	}

}