package com.falabellasellers.preaprobados;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cliente implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Margen")
	private java.lang.Double margen;
	@org.kie.api.definition.type.Label("TramoSII")
	private java.lang.Integer tramoSII;
	@org.kie.api.definition.type.Label("SectorEconomico")
	private java.lang.String sectorEconomico;
	@org.kie.api.definition.type.Label("VentaCastigada")
	private Integer ventaCastigada;
	@org.kie.api.definition.type.Label("MercadoObjetivo")
	private java.lang.Boolean mercadoObjetivo;
	@org.kie.api.definition.type.Label("Tamaño")
	private java.lang.String tamaño;

	@org.kie.api.definition.type.Label("Letra_sector")
	private java.lang.String letra_Sector;

	@org.kie.api.definition.type.Label("VentaCTE")
	private Integer ventaCTE;

	@org.kie.api.definition.type.Label("VentaMarket")
	private java.lang.Integer ventaMarket;

	@org.kie.api.definition.type.Label("TipoVenta")
	private java.lang.Integer tipoVenta;

	public Cliente() {
	}

	public java.lang.Double getMargen() {
		return this.margen;
	}

	public void setMargen(java.lang.Double margen) {
		this.margen = margen;
	}

	public java.lang.Integer getTramoSII() {
		return this.tramoSII;
	}

	public void setTramoSII(java.lang.Integer tramoSII) {
		this.tramoSII = tramoSII;
	}

	public java.lang.String getSectorEconomico() {
		return this.sectorEconomico;
	}

	public void setSectorEconomico(java.lang.String sectorEconomico) {
		this.sectorEconomico = sectorEconomico;
	}

	public java.lang.Boolean getMercadoObjetivo() {
		return this.mercadoObjetivo;
	}

	public void setMercadoObjetivo(java.lang.Boolean mercadoObjetivo) {
		this.mercadoObjetivo = mercadoObjetivo;
	}

	public java.lang.String getTamaño() {
		return this.tamaño;
	}

	public void setTamaño(java.lang.String tamaño) {
		this.tamaño = tamaño;
	}

	public java.lang.String getLetra_Sector() {
		return this.letra_Sector;
	}

	public void setLetra_Sector(java.lang.String letra_Sector) {
		this.letra_Sector = letra_Sector;
	}

	public java.lang.Integer getVentaMarket() {
		return this.ventaMarket;
	}

	public void setVentaMarket(java.lang.Integer ventaMarket) {
		this.ventaMarket = ventaMarket;
	}

	public java.lang.Integer getTipoVenta() {
		return this.tipoVenta;
	}

	public void setTipoVenta(java.lang.Integer tipoVenta) {
		this.tipoVenta = tipoVenta;
	}

	public java.lang.Integer getVentaCastigada() {
		return this.ventaCastigada;
	}

	public void setVentaCastigada(java.lang.Integer ventaCastigada) {
		this.ventaCastigada = ventaCastigada;
	}

	public java.lang.Integer getVentaCTE() {
		return this.ventaCTE;
	}

	public void setVentaCTE(java.lang.Integer ventaCTE) {
		this.ventaCTE = ventaCTE;
	}

	public Cliente(java.lang.Double margen, java.lang.Integer tramoSII,
			java.lang.String sectorEconomico, java.lang.Integer ventaCastigada,
			java.lang.Boolean mercadoObjetivo, java.lang.String tamaño,
			java.lang.String letra_Sector, java.lang.Integer ventaCTE,
			java.lang.Integer ventaMarket, java.lang.Integer tipoVenta) {
		this.margen = margen;
		this.tramoSII = tramoSII;
		this.sectorEconomico = sectorEconomico;
		this.ventaCastigada = ventaCastigada;
		this.mercadoObjetivo = mercadoObjetivo;
		this.tamaño = tamaño;
		this.letra_Sector = letra_Sector;
		this.ventaCTE = ventaCTE;
		this.ventaMarket = ventaMarket;
		this.tipoVenta = tipoVenta;
	}

}