package com.falabellasellers.preaprobados;



/**
 * This class was automatically generated by the data modeler tool.
 */

public class CompraVentaMensualesObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @org.kie.api.definition.type.Label("periodo")
    private String periodo;
    @org.kie.api.definition.type.Label("venta")
    private String venta;
    @org.kie.api.definition.type.Label("compra")
    private String compra;

    public CompraVentaMensualesObject() {
    }

    public String getPeriodo() {
        return periodo;
    }

    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }

    public CompraVentaMensualesObject withPeriodo(String periodo) {
        this.periodo = periodo;
        return this;
    }

    public String getVenta() {
        return venta;
    }

    public void setVenta(String venta) {
        this.venta = venta;
    }

    public CompraVentaMensualesObject withVenta(String venta) {
        this.venta = venta;
        return this;
    }

    public String getCompra() {
        return compra;
    }

    public void setCompra(String compra) {
        this.compra = compra;
    }
    public CompraVentaMensualesObject withCompra(String compra) {
        this.compra = compra;
        return this;
    }

    public CompraVentaMensualesObject(String periodo, String venta, String compra) {
        this.periodo = periodo;
        this.venta = venta;
        this.compra = compra;
    }
}