package com.falabellasellers.preaprobados;

import cl.falabella.pylon.mappings.linio.ResultLinio;
import cl.falabella.pylon.mappings.linio.LinioSales;
import cl.falabella.pylon.mappings.linio.LinioSale;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LinioObject extends ResultLinio implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public LinioObject() {
        super();
    }


}