package com.falabellasellers.preaprobados;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Sectores implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Sector")
	private java.lang.String sector;
	@org.kie.api.definition.type.Label("Margen")
	private java.lang.Double margen;

	public Sectores() {
	}

	public java.lang.String getSector() {
		return this.sector;
	}

	public void setSector(java.lang.String sector) {
		this.sector = sector;
	}

	public java.lang.Double getMargen() {
		return this.margen;
	}

	public void setMargen(java.lang.Double margen) {
		this.margen = margen;
	}

	public Sectores(java.lang.String sector, java.lang.Double margen) {
		this.sector = sector;
		this.margen = margen;
	}

}