package com.falabellasellers.preaprobados;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TramosSII implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("TramoSii")
	private java.lang.Integer tramoSii;
	@org.kie.api.definition.type.Label("Descripcion")
	private java.lang.String descripcion;
	@org.kie.api.definition.type.Label("Tope")
	private Double topeInferior;
	@org.kie.api.definition.type.Label("VentaAño")
	private Double ventaAño;
	@org.kie.api.definition.type.Label("VentaMes")
	private Double ventaMes;
	@org.kie.api.definition.type.Label("VentaCastigada")
	private Double ventaCastigada;
	@org.kie.api.definition.type.Label("Mercado")
	private java.lang.Boolean mercadoObjetivo;

	@org.kie.api.definition.type.Label(value = "Tamaño")
	private java.lang.String tamañoEmpresa;

	public TramosSII() {
	}

	public java.lang.Integer getTramoSii() {
		return this.tramoSii;
	}

	public void setTramoSii(java.lang.Integer tramoSii) {
		this.tramoSii = tramoSii;
	}

	public java.lang.String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(java.lang.String descripcion) {
		this.descripcion = descripcion;
	}

	public java.lang.Boolean getMercadoObjetivo() {
		return this.mercadoObjetivo;
	}

	public void setMercadoObjetivo(java.lang.Boolean mercadoObjetivo) {
		this.mercadoObjetivo = mercadoObjetivo;
	}

	public java.lang.Double getTopeInferior() {
		return this.topeInferior;
	}

	public void setTopeInferior(java.lang.Double topeInferior) {
		this.topeInferior = topeInferior;
	}

	public java.lang.Double getVentaAño() {
		return this.ventaAño;
	}

	public void setVentaAño(java.lang.Double ventaAño) {
		this.ventaAño = ventaAño;
	}

	public java.lang.Double getVentaMes() {
		return this.ventaMes;
	}

	public void setVentaMes(java.lang.Double ventaMes) {
		this.ventaMes = ventaMes;
	}

	public java.lang.Double getVentaCastigada() {
		return this.ventaCastigada;
	}

	public void setVentaCastigada(java.lang.Double ventaCastigada) {
		this.ventaCastigada = ventaCastigada;
	}

	public java.lang.String getTamañoEmpresa() {
		return this.tamañoEmpresa;
	}

	public void setTamañoEmpresa(java.lang.String tamañoEmpresa) {
		this.tamañoEmpresa = tamañoEmpresa;
	}

	public TramosSII(java.lang.Integer tramoSii, java.lang.String descripcion,
			java.lang.Double topeInferior, java.lang.Double ventaAño,
			java.lang.Double ventaMes, java.lang.Double ventaCastigada,
			java.lang.Boolean mercadoObjetivo, java.lang.String tamañoEmpresa) {
		this.tramoSii = tramoSii;
		this.descripcion = descripcion;
		this.topeInferior = topeInferior;
		this.ventaAño = ventaAño;
		this.ventaMes = ventaMes;
		this.ventaCastigada = ventaCastigada;
		this.mercadoObjetivo = mercadoObjetivo;
		this.tamañoEmpresa = tamañoEmpresa;
	}

}