package com.falabellasellers.preaprobados;

import cl.datamart.pylon.TributaryInfoResponse;
import cl.datamart.pylon.mappings.cte.CTE;

import java.io.IOException;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TributaryResponseObject extends TributaryInfoResponse implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TributaryResponseObject() {
        super();
    }

    @Override
    public CTE deserializeResponse() throws IOException {
        return super.deserializeResponse();
    }
}