package com.falabellasellers.preaprobados;

import java.util.Objects;

/**
 * This class was automatically generated by the data modeler tool.
 */

public final class Utilitarios {


    public static final String NO_INFO = "SIN INFORMACION";

    private Utilitarios() {
    }

    public static String getFirstLetterOrDefaultValue(String word) {

        if (Objects.nonNull(word) && !word.isEmpty()) {
            if (word.toUpperCase().equalsIgnoreCase(NO_INFO)) {
                return "v";
            } else {
                final String firstLetter = word.substring(0, 1);
                return firstLetter.toLowerCase();
            }

        }

        return "v";
    }


}