package com.falabellasellers.preaprobados;

import java.util.Objects;

/**
 * This class was automatically generated by the data modeler tool.
 */

public final class Utilitarios implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private Utilitarios() {
    }

    public static String getFirstLetterOrDefaultValue(String word) {

        if (Objects.nonNull(word) && !word.isEmpty()) {
            if (word.toUpperCase().equalsIgnoreCase("SIN INFORMACION")) {
                return "v";
            } else {
                final String firstLetter = word.substring(0, 1);
                return firstLetter.toLowerCase();
            }

        }

        return "v";
    }


}