package com.falabellasellers.preaprobados;

import cl.datamart.pylon.mappings.cte.Extras;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VentasCTE extends Extras implements java.io.Serializable {

	static final long serialVersionUID = -15656565L;

	public VentasCTE() {
		super();
	}

}